default:
  target: dev
  outputs:
    dev:
      catalog: data_saturday
      schema: default
      host: adb-984752964297111.11.azuredatabricks.net
      http_path: /sql/1.0/warehouses/d1184b8c2a8a87eb
      threads: 6
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      type: databricks
